name: 2.7 4.3 Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 2.7
      - name: Caching
        uses: actions/cache@v3.2.3
        with:
          path: |
            eggs
          key: cache-Py2.7-Plone4.3
      - name: Install venv
        run: |
          pip install virtualenv
          make -f Makefile-py27 plone43
      - name: Run unit tests
        run: |
          bin/pytest
